version: "3"

services:
  server:
    build: ./
    environment:
      - LOYALTY_API
      - APIKEY
      - PORT
      - LOGLEVEL
      - LOGPATH
    network_mode: "host"
    volumes:
      - /home/docker/loyalty-rkeeper-logs/:/logs
